version: "3"
services:
  sw-ts:
    container_name: sw-ts
    image: sh7/sw-ts:v0.1
    command: sleep infinity
    ports:
      - 8888:8888
      - 5000:5000
    volumes:
      - C:\Users\sh70k\project:/project
      - C:\Users\sh70k\data:/data