version: "3"
services:
  sw-ts:
    container_name: sw-ts
    image: python39-pytorch  # sh7/sw-ts:v0.1
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - 8888:8888
      # - 5000:5000
    volumes:
      - ~/projects:/project
      - ~/data:/data